# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: db-pv
# spec:
#   capacity:
#     storage: 1Gi
#   volumeMode: Filesystem
#   accessModes:
#     - ReadWriteOnce
#   persistentVolumeReclaimPolicy: Retain
#   storageClassName: manual
#   local:
#     path: /mnt/disks/st-mysql
#   nodeAffinity:
#     required:
#       nodeSelectorTerms:
#         - matchExpressions:
#             - key: kubernetes.io/hostname
#               operator: In
#               values: ['minikube']
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: db-pvc
# spec:
#   resources:
#     requests:
#       storage: 1Gi
#   volumeMode: Filesystem
#   accessModes:
#     - ReadWriteOnce
#   storageClassName: manual

# ---
# apiVersion: v1
# kind: PersistentVolume
# metadata:
#   name: sql-backup-pv
# spec:
#   storageClassName: db-backup-storage
#   capacity:
#     storage: 1Gi
#   accessModes:
#     - ReadOnlyMany
#   hostPath:
#     path: /mnt/e/db
# ---
# apiVersion: v1
# kind: PersistentVolumeClaim
# metadata:
#   name: sql-backup-pvc
# spec:
#   storageClassName: db-backup-storage
#   accessModes:
#     - ReadOnlyMany
#   resources:
#     requests:
#       storage: 1Gi