apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
        listen 80;

        # WordPress files තියෙන තැන
        root /var/www/html;
        index index.php index.html;

        location / {
            # try_files $uri $uri/ /index.php?$args;
            try_files $uri $uri/ /index.php$is_args$args;
        }
        
        location = /wp-content/debug.log {
            default_type text/plain;
        }

        location ~ ^/wp-json/ {
            try_files $uri $uri/ /index.php$is_args$args;
        }

        gzip on;
        gzip_types text/plain text/css application/json application/javascript text/xml;

        location ~* \.(js|css|png|jpg|jpeg|gif|ico|svg)$ {
            expires 30d;
            add_header Cache-Control "public, no-transform";
        }

        location ~ \.php$ {
            fastcgi_pass wp-service:9000; 
            fastcgi_index index.php;
            include fastcgi_params;
            fastcgi_param SCRIPT_FILENAME /var/www/html$fastcgi_script_name;

            fastcgi_read_timeout 300;
            fastcgi_connect_timeout 300;
            fastcgi_send_timeout 300;
            fastcgi_buffers 16 16k;
            fastcgi_buffer_size 32k;
        }
    }