apiVersion: v1
kind: ConfigMap
metadata:
  name: php-ini-file
data:
  php.ini: |
    opcache.memory_consumption=128
    opcache.interned_strings_buffer=8
    opcache.max_accelerated_files=4000
    opcache.fast_shutdown=1
    opcache.revalidate_freq=60
    opcache.validate_timestamps=1
    memory_limit = 512M
    max_execution_time = 300
    upload_max_filesize = 128M
    post_max_size = 128M
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: wp-extra-config
data:
  WORDPRESS_CONFIG_EXTRA: |
    /* Performance & Security */
    define('WP_MEMORY_LIMIT', '1024M');
    define('WP_MAX_MEMORY_LIMIT', '2048M');
    define('DISALLOW_FILE_EDIT', true);
    
    /* Debugging off for speed */
    define('WP_DEBUG_LOG', true);
    define('WP_DEBUG_DISPLAY', true);
    define('SAVEQUERIES', true);
    
    /* Redis Object Cache Config */
    define('WP_REDIS_HOST', 'redis');
    define('WP_REDIS_PORT', 6379);
    define('WP_REDIS_DATABASE', 0);
    define('WP_REDIS_TIMEOUT', 1);
    define('WP_REDIS_READ_TIMEOUT', 1);

    define('FS_METHOD', 'direct');
    
    /* External Request Management (Fixes the 5s lag) */
    define('WP_HTTP_BLOCK_EXTERNAL', false);
    define('WP_ACCESSIBLE_HOSTS', 'api.wordpress.org,*.elementor.com,connect.elementor.com');
